version: '3.1'

services:
  db:
    container_name: auth-postgres
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
      TZ: 'GMT+5'
      PGTZ: 'GMT+5'
    volumes:
      - ./runtime/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432

  admin:
    container_name: auth-postgres-admin
    image: adminer
    depends_on:
      -  db
    ports:
      - "8181:8080"